true="./${obj_dir}/write_true"
false="./${obj_dir}/write_false"

test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${false} 3  &&  ${true}  4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3  ||  ${false} 4  &&  ${false} 5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${true}  2 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  ||  ${true}  2 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${true}  3  ||  ${true}  4  ||  ${true}  5  &&  ${false} 6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${true}  4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${true}  3  ||  ${true}  4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3  &&  ${true}  4  &&  ${true}  5  ||  ${true}  6 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${false} 3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  ||  ${false} 3  ||  ${true}  4  &&  ${false} 5  &&  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  ||  ${true}  3  &&  ${false} 4  ||  ${false} 5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${true}  4  &&  ${true}  5  ||  ${true}  6 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  ||  ${false} 5  ||  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3  &&  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${true}  2  ||  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  ||  ${true}  4  ||  ${false} 5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4  ||  ${false} 5  ||  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${true}  3  ||  ${true}  4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4  &&  ${false} 5  ||  ${false} 6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5  ||  ${false} 6  ||  ${false} 7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4  &&  ${false} 5 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  &&  ${false} 5  &&  ${true}  6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4  &&  ${true}  5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${true}  2  &&  ${false} 3  &&  ${true}  4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5  &&  ${true}  6  ||  ${false} 7 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  ||  ${true}  4  ||  ${true}  5  &&  ${false} 6  ||  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  &&  ${true}  4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${false} 4  ||  ${false} 5  ||  ${false} 6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${true}  5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4  &&  ${true}  5  &&  ${true}  6 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5  &&  ${false} 6  ||  ${false} 7 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  &&  ${false} 5  ||  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  ||  ${false} 4  &&  ${false} 5  ||  ${true}  6  ||  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${false} 3  ||  ${true}  4  ||  ${false} 5  &&  ${true}  6  ||  ${false} 7 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  ||  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  ||  ${false} 2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5  &&  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  ||  ${true}  3  ||  ${false} 4  ||  ${true}  5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  &&  ${true}  3  &&  ${true}  4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  ||  ${false} 3  ||  ${false} 4  &&  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${true}  4  ||  ${false} 5 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${false} 4  ||  ${true}  5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2  &&  ${true}  3  &&  ${true}  4  ||  ${false} 5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${false} 5  &&  ${true}  6  &&  ${true}  7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${false} 2  ||  ${true}  3 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${false} 4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  &&  ${false} 2  ||  ${true}  3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${true}  3  &&  ${false} 4  ||  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5  ||  ${false} 6  ||  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  ||  ${true}  4 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  &&  ${true}  3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  &&  ${false} 4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${true}  3  ||  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${true}  3  &&  ${true}  4  &&  ${false} 5  &&  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  &&  ${false} 2 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${false} 5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${true}  4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5  &&  ${true}  6 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  &&  ${true}  5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${true}  2  ||  ${false} 3  &&  ${true}  4  ||  ${false} 5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3  ||  ${false} 4  ||  ${true}  5  ||  ${false} 6  &&  ${true}  7 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5  &&  ${false} 6  &&  ${true}  7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  ||  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4  &&  ${false} 5  ||  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  &&  ${false} 5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  ||  ${false} 2 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${false} 4  &&  ${false} 5  ||  ${true}  6 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4  &&  ${true}  5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3 "
test_launch "${true}  okalm  &&  ${false} 0 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${false} 5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${false} 4  &&  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${true}  3  ||  ${false} 4  ||  ${true}  5  &&  ${false} 6  ||  ${false} 7 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  &&  ${false} 2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  ||  ${false} 4 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${false} 4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  ||  ${true}  2  ||  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${false} 3  ||  ${true}  4  ||  ${false} 5  &&  ${false} 6  ||  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${false} 3 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  ||  ${true}  3  ||  ${true}  4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4  ||  ${false} 5  &&  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${false} 2 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4  &&  ${false} 5  ||  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${false} 5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${false} 3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${true}  4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3 "
test_launch "${false} okalm  &&  ${false} 0 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5  ||  ${false} 6  &&  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4  ||  ${true}  5  ||  ${false} 6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2  ||  ${false} 3  ||  ${true}  4  &&  ${false} 5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  &&  ${false} 2 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  ||  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  ||  ${false} 5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4  ||  ${false} 5  &&  ${false} 6  ||  ${false} 7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  ||  ${false} 5  ||  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${true}  2  ||  ${false} 3  ||  ${false} 4  ||  ${true}  5 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  ||  ${false} 2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  &&  ${true}  5  &&  ${false} 6  &&  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4  &&  ${true}  5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${false} 3 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2  &&  ${false} 3  &&  ${false} 4  &&  ${true}  5  &&  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${false} 4  &&  ${false} 5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4  ||  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${true}  4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${true}  4  ||  ${true}  5  &&  ${false} 6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  &&  ${true}  5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${true}  3  ||  ${true}  4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5  &&  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  ||  ${false} 3 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${false} 3  ||  ${true}  4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  ||  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${true}  2 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${true}  3  ||  ${false} 4  ||  ${false} 5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5  ||  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4  &&  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${false} 4  ||  ${false} 5  &&  ${true}  6  &&  ${false} 7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4  ||  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4  &&  ${false} 5  ||  ${false} 6  &&  ${true}  7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4  &&  ${true}  5  &&  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3  &&  ${true}  4  &&  ${true}  5  &&  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${true}  3  &&  ${false} 4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5  ||  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  &&  ${true}  5  &&  ${false} 6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  ||  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${true}  2 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${false} 4  &&  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  ||  ${false} 2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  ||  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${false} 2 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${false} 4  &&  ${false} 5  ||  ${false} 6 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${true}  4  ||  ${false} 5  ||  ${false} 6 "
test_launch "${true}  okalm  &&  ${true}  0 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${true}  4  &&  ${false} 5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${false} 4  &&  ${true}  5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  &&  ${true}  3  ||  ${true}  4  &&  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${false} 3  ||  ${true}  4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3  ||  ${false} 4  ||  ${true}  5  ||  ${true}  6  &&  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4  &&  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${true}  4  &&  ${false} 5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${false} 4  &&  ${true}  5  &&  ${false} 6  &&  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${false} 3  ||  ${false} 4  &&  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  &&  ${false} 4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3  ||  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  ||  ${false} 2  &&  ${true}  3  ||  ${true}  4  ||  ${false} 5 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${true}  4  &&  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2  ||  ${true}  3  &&  ${false} 4  &&  ${false} 5  &&  ${true}  6  &&  ${true}  7 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${false} 4  ||  ${true}  5  ||  ${false} 6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${true}  4  &&  ${true}  5  &&  ${false} 6  ||  ${false} 7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4  &&  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  ||  ${true}  4  &&  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  ||  ${false} 2  ||  ${true}  3  ||  ${true}  4  ||  ${true}  5  &&  ${true}  6  ||  ${false} 7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${true}  4  ||  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4  ||  ${false} 5  ||  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5  ||  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${true}  4  ||  ${false} 5  &&  ${true}  6  &&  ${true}  7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${false} 4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5  ||  ${true}  6  ||  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${true}  3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  &&  ${false} 4 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${true}  2 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${true}  4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${false} 5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${true}  4  ||  ${false} 5  &&  ${false} 6  &&  ${false} 7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4  &&  ${false} 5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  &&  ${true}  3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${false} 5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  ||  ${false} 2  &&  ${true}  3  ||  ${true}  4  ||  ${true}  5  ||  ${false} 6  ||  ${false} 7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${true}  3  &&  ${false} 4  ||  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${true}  2  ||  ${false} 3  ||  ${true}  4  &&  ${false} 5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  ||  ${true}  2  ||  ${true}  3  ||  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${true}  4  &&  ${true}  5  ||  ${false} 6  &&  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${true}  3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${true}  3  ||  ${false} 4  ||  ${false} 5  ||  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4  ||  ${false} 5  ||  ${false} 6  ||  ${false} 7 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5  ||  ${false} 6 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  &&  ${false} 4  &&  ${false} 5  ||  ${false} 6  ||  ${false} 7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4  &&  ${false} 5  &&  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  &&  ${true}  5  &&  ${false} 6  ||  ${false} 7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  ||  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5  ||  ${false} 6  ||  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  ||  ${true}  5  ||  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${true}  4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${true}  3  &&  ${true}  4  ||  ${true}  5  &&  ${true}  6  &&  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${false} 5  &&  ${true}  6  ||  ${false} 7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2  &&  ${true}  3 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${false} 3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  &&  ${true}  4  ||  ${true}  5  ||  ${true}  6  ||  ${false} 7 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${true}  2  ||  ${true}  3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${true}  3  ||  ${false} 4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3  ||  ${false} 4 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${false} 4  &&  ${true}  5  &&  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${false} 4  ||  ${true}  5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  ||  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${false} 5  &&  ${false} 6  &&  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5  ||  ${true}  6  &&  ${true}  7 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${false} 4 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${false} 5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  ||  ${true}  3  &&  ${false} 4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1 "
test_launch "${true}  okalm  ||  ${true}  0 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  ||  ${true}  3  &&  ${false} 4  &&  ${true}  5  ||  ${true}  6  &&  ${true}  7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${false} 5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${false} 3  ||  ${true}  4  &&  ${false} 5  &&  ${true}  6 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  &&  ${true}  3 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  ||  ${false} 5  &&  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3  ||  ${false} 4  ||  ${false} 5  ||  ${true}  6  ||  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  ||  ${true}  2  ||  ${false} 3  ||  ${false} 4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${false} 5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${false} 3  ||  ${false} 4  ||  ${false} 5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${true}  3  &&  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3  ||  ${true}  4  ||  ${false} 5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  &&  ${true}  4  &&  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${false} 2 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3  ||  ${false} 4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${true}  3  ||  ${true}  4  ||  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3  ||  ${true}  4  &&  ${true}  5  &&  ${false} 6  &&  ${true}  7 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${true}  5 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4  ||  ${false} 5 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3  ||  ${false} 4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4  ||  ${false} 5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5  &&  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${true}  1  &&  ${false} 2  ||  ${true}  3 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${true}  4 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  ||  ${false} 4  ||  ${true}  5  &&  ${false} 6  &&  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  &&  ${true}  4 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4  &&  ${false} 5  ||  ${false} 6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${true}  2  ||  ${true}  3  ||  ${true}  4  ||  ${true}  5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5  ||  ${true}  6  ||  ${false} 7 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${true}  1  &&  ${true}  2  &&  ${false} 3  &&  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${true}  1  &&  ${false} 2 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  &&  ${true}  2  &&  ${false} 3  &&  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3  &&  ${false} 4  ||  ${false} 5 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  ||  ${false} 3  ||  ${false} 4  ||  ${true}  5  ||  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${false} 4 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2  ||  ${true}  3 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  ||  ${true}  3 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${true}  4  ||  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  ||  ${false} 3 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  &&  ${true}  2 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2 "
test_launch "${false} okalm  ||  ${true}  0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4  &&  ${true}  5  ||  ${false} 6  &&  ${true}  7 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3  &&  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3  ||  ${true}  4  ||  ${true}  5 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${false} 3 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${false} 4  ||  ${false} 5 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${true}  3  ||  ${false} 4  &&  ${false} 5  &&  ${true}  6  &&  ${false} 7 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2  ||  ${true}  3  ||  ${true}  4  ||  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5  &&  ${true}  6 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  &&  ${false} 5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4  ||  ${true}  5  ||  ${true}  6  ||  ${false} 7 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2  &&  ${true}  3  ||  ${true}  4 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${false} 4  ||  ${false} 5  &&  ${true}  6  &&  ${true}  7 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${false} 5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  ||  ${true}  2  ||  ${false} 3  &&  ${false} 4  &&  ${false} 5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  ||  ${true}  2 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${true}  2  &&  ${true}  3  &&  ${false} 4  ||  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${true}  2  &&  ${false} 3  ||  ${false} 4  &&  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${false} 3  &&  ${true}  4  ||  ${false} 5  &&  ${true}  6  &&  ${false} 7 "
test_launch "${false} okalm  &&  ${false} 0  &&  ${false} 1  &&  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${false} 4  ||  ${false} 5  ||  ${true}  6 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${false} 2  ||  ${true}  3  ||  ${false} 4  &&  ${true}  5  ||  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  ||  ${true}  2  ||  ${true}  3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  &&  ${false} 3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${true}  1  ||  ${false} 2  ||  ${true}  3  ||  ${false} 4  &&  ${true}  5  &&  ${true}  6  &&  ${true}  7 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2  &&  ${false} 3  &&  ${false} 4  ||  ${true}  5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  &&  ${true}  2  &&  ${true}  3  &&  ${false} 4  &&  ${false} 5  &&  ${true}  6  ||  ${true}  7 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  &&  ${true}  2 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  ||  ${true}  2  &&  ${true}  3  &&  ${true}  4  ||  ${true}  5  &&  ${false} 6 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3  ||  ${false} 4  ||  ${true}  5  &&  ${false} 6 "
test_launch "${false} okalm  ||  ${false} 0  ||  ${false} 1  &&  ${true}  2  ||  ${false} 3  ||  ${false} 4  ||  ${true}  5  ||  ${true}  6  &&  ${false} 7 "
test_launch "${true}  okalm  &&  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  &&  ${false} 4  ||  ${true}  5  &&  ${true}  6 "
test_launch "${false} okalm  ||  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${false} 3  &&  ${true}  4  &&  ${false} 5  ||  ${true}  6 "
test_launch "${false} okalm  ||  ${true}  0 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${true}  2  ||  ${false} 3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${false} 1  &&  ${false} 2  ||  ${true}  3  &&  ${true}  4  ||  ${true}  5  ||  ${true}  6 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4  ||  ${false} 5  ||  ${false} 6 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${false} 2  &&  ${true}  3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${true}  1  ||  ${true}  2  &&  ${false} 3  ||  ${true}  4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${false} 1  &&  ${false} 2  &&  ${false} 3  &&  ${false} 4 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${false} 2  &&  ${true}  3  &&  ${true}  4 "
test_launch "${false} okalm  &&  ${true}  0  &&  ${true}  1  ||  ${false} 2 "
test_launch "${false} okalm  &&  ${true}  0  ||  ${false} 1  &&  ${false} 2 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${false} 4  ||  ${true}  5  &&  ${false} 6  ||  ${true}  7 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2  &&  ${false} 3 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${false} 1  ||  ${false} 2  &&  ${false} 3 "
test_launch "${true}  okalm  &&  ${false} 0  ||  ${false} 1  ||  ${false} 2  ||  ${false} 3  &&  ${false} 4 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${true}  1  &&  ${true}  2  ||  ${false} 3  ||  ${true}  4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  ||  ${true}  2  ||  ${true}  3  ||  ${false} 4 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1 "
test_launch "${true}  okalm  ||  ${true}  0  ||  ${false} 1  &&  ${true}  2  ||  ${true}  3  ||  ${true}  4 "
test_launch "${true}  okalm  ||  ${true}  0  &&  ${false} 1  &&  ${false} 2  &&  ${true}  3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  ||  ${false} 2  &&  ${true}  3  ||  ${false} 4  &&  ${true}  5  ||  ${true}  6  ||  ${false} 7 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${false} 1  ||  ${true}  2  &&  ${true}  3  ||  ${true}  4 "
test_launch "${true}  okalm  &&  ${true}  0  &&  ${true}  1  &&  ${true}  2  &&  ${false} 3  &&  ${true}  4  &&  ${true}  5 "
test_launch "${true}  okalm  ||  ${false} 0  ||  ${true}  1  &&  ${true}  2  ||  ${true}  3  &&  ${true}  4  &&  ${false} 5  &&  ${false} 6 "
test_launch "${false} okalm  &&  ${false} 0  ||  ${false} 1  ||  ${true}  2 "
test_launch "${true}  okalm  &&  ${true}  0  ||  ${true}  1  &&  ${false} 2  ||  ${false} 3 "
test_launch "${true}  okalm  ||  ${false} 0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3  &&  ${true}  4 "
test_launch "${false} okalm  ||  ${true}  0  &&  ${true}  1  &&  ${false} 2  &&  ${false} 3  ||  ${true}  4 "
