# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    test_expansions_substring_removal.sh               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jmartel <jmartel@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/05/21 16:00:50 by jmartel           #+#    #+#              #
#    Updated: 2019/11/26 08:30:46 by jmartel          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

launch "substring_removal"
	launch_show "# and ## no pattern matching"
	test_launch 'param="Okalmos Speculos"' 'echo ${param#}'
	test_launch 'param="Okalmos Speculos"' 'echo ${#}'
	test_launch 'param="Okalmos Speculos"' 'echo ${#os}'
	test_launch 'param="Okalmos Speculos"' 'echo ${#param}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#param}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#s}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param# Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#kalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#kamos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#Oka}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param#OkalmosSpeculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${var#Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##}'
	test_launch 'param="Okalmos Speculos"' 'echo ${##}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##param}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##s}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param## Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##kalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##kamos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##Oka}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param##OkalmosSpeculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${var##Okalmos Speculos}'

	launch_show "% and %% no pattern matching"
	test_launch 'param="Okalmos Speculos"' 'echo ${param%}'
	test_launch 'param="Okalmos Speculos"' 'echo ${%}'
	test_launch 'param="Okalmos Speculos"' 'echo ${%os}'
	test_launch 'param="Okalmos Speculos"' 'echo ${%param}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%param}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%s}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param% Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%kalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%kamos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%Oka}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%OkalmosSpeculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${var%Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%}'
	test_launch 'param="Okalmos Speculos"' 'echo ${%%}'
	test_launch 'param="Okalmos Speculos"' 'echo ${%%os}'
	test_launch 'param="Okalmos Speculos"' 'echo ${%%param}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%param}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%s}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%% Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%kalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%kamos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%Oka}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%Okalmos Speculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${param%%OkalmosSpeculos}'
	test_launch 'param="Okalmos Speculos"' 'echo ${var%%Okalmos Speculos}'

	launch_show "% pattern matching"
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%/}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%/}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%*.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%*.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%?.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%?.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%%?.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%???}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%???}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%[a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%[a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%?[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%?[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%?[!a-z]}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param%%?[!a-z]}'
	test_launch 'param="./dir/subdir/file.c" var="./dir/"'  'echo ${param%%$var}'
	test_launch 'param="./dir/subdir/file.c" var="/file.c"'  'echo ${param%%$var}'

	launch_show "# pattern matching"
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#/}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##/}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#*.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##*.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#?.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##?.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param###?.c}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#???}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##???}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#[a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##[a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#?[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##?[!a-z]*}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param#?[!a-z]}'
	test_launch 'param="./dir/subdir/file.c"'  'echo ${param##?[!a-z]}'
	test_launch 'param="./dir/subdir/file.c" var="./dir/"'  'echo ${param##$var}'
	test_launch 'param="./dir/subdir/file.c" var="/file.c"'  'echo ${param##$var}'
	
	launch_show "found on the internet"
	
	test_launch 'string="hello-world" prefix="hell" suffix="ld"' 'foo=${string#"$prefix"} ; echo $? $string'
	test_launch 'string="hello-world" prefix="hell" suffix="ld"' 'foo=${foo%"$suffix"} ; echo $? $string'
	test_launch 'string="hello-world" prefix="hell" suffix="ld"' 'foo=${string#"$prefix"} ; foo=${foo%"$suffix"} ; echo $? $string'
	test_launch 'var="Welcome to the geekstuff"' 'echo ${#var}'
	test_launch 'filename="bash.string.txt"' 'echo ${filename#*.}' 'echo ${filename%.*}'
	test_launch 'filename="bash.string.txt"' '${filename##*.}' '${filename%%*.}'

	launch_show 'randomly created'
	test_launch 'param=Okalm'  'word' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '?' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '??' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '?*?' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '[A-Z][!a-z]' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '[A-Z][!a-z]?' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '[A-Z][!a-z]?*' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '*/' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '/*' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '?/' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '?/' 'echo ${param%word=}'
	test_launch 'param=Okalm'  'one?' 'echo ${param%word=}'
	test_launch 'param=Okalm'  'th???' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '*/*' 'echo ${param%word=}'
	test_launch 'param=Okalm'  '[\[]' 'echo ${param%word=}'
	test_launch 'param=Okalm'  'word' 'echo ${param%}'
	test_launch 'param=Okalm'  '?' 'echo ${param%}'
	test_launch 'param=Okalm'  '??' 'echo ${param%}'
	test_launch 'param=Okalm'  '?*?' 'echo ${param%}'
	test_launch 'param=Okalm'  '[A-Z][!a-z]' 'echo ${param%}'
	test_launch 'param=Okalm'  '[A-Z][!a-z]?' 'echo ${param%}'
	test_launch 'param=Okalm'  '[A-Z][!a-z]?*' 'echo ${param%}'

	# test_launch 'param=""'  'echo ${param%}'
	# test_launch 'param=""'  'echo ${param%}'

finish
